const SHOP_DATA = {
  team1: {
    id: 1,
    title: "Team1",
    Players: [
      {
        id: 1,
        name: "Adam Milne",
        matches: 1,
        runs: 0,
        wickets: 0,
        img: "https://static.iplt20.com/players/284/434.png",
      },
      {
        id: 2,
        name: "Aditya Tare",
        matches: 0,
        runs: 0,
        wickets: 0,
        img: "https://static.iplt20.com/players/210/99.png",
      },
      {
        id: 3,
        name: "Hardik Pandya",
        matches: 7,
        runs: 52,
        wickets: 0,
        img: "https://static.iplt20.com/players/210/2740.png",
      },
      {
        id: 4,
        name: "Ishan Kishan",
        matches: 5,
        runs: 73,
        wickets: 0,
        img: "https://static.iplt20.com/players/210/2975.png",
      },
      // {
      //   id: 5,
      //   name: "Jasprit Bumrah",
      //   matches: 7,
      //   runs: 4,
      //   wickets: 6,
      //   img: "https://static.iplt20.com/players/210/1124.png",
      // },
    ],
  },
  team2: {
    id: 2,
    title: "Team2",
    Players: [
      {
        id: 6,
        name: "Jayant Yadav",
        matches: 3,
        runs: 23,
        wickets: 1,
        img: "https://static.iplt20.com/players/210/1740.png",
      },
      {
        id: 7,
        name: "Kieron Pollard",
        matches: 7,
        runs: 168,
        wickets: 3,
        img: "https://static.iplt20.com/players/210/210.png",
      },
      {
        id: 8,
        name: "Krunal Pandya",
        matches: 7,
        runs: 100,
        wickets: 3,
        img: "https://static.iplt20.com/players/210/3183.png",
      },
      {
        id: 9,
        name: "Rahul Chahar",
        matches: 7,
        runs: 14,
        wickets: 11,
        img: "https://static.iplt20.com/players/210/3763.png",
      },
      // {
      //   id: 10,
      //   name: "Trent Boult",
      //   matches: 7,
      //   runs: 1,
      //   wickets: 8,
      //   img: "https://static.iplt20.com/players/210/969.png",
      // },
    ],
  },
  team3: {
    id: 3,
    title: "Team3",
    Players: [
      {
        id: 11,
        name: "Marco Jansen",
        matches: 2,
        runs: 0,
        wickets: 2,
        img: "https://static.iplt20.com/players/210/17068.png",
      },
      {
        id: 12,
        name: "Piyush Chawla",
        matches: 0,
        runs: 0,
        wickets: 2,
        img: "https://static.iplt20.com/players/210/76.png",
      },
      {
        id: 13,
        name: "Chris Lynn",
        matches: 1,
        runs: 49,
        wickets: 0,
        img: "https://static.iplt20.com/players/210/179.png",
      },
      {
        id: 14,
        name: "Dhawal Kulkarni",
        matches: 1,
        runs: 4,
        wickets: 1,
        img: "https://static.iplt20.com/players/210/101.png",
      },
      // {
      //   id: 15,
      //   name: "Adam Milne",
      //   matches: 0,
      //   runs: 0,
      //   wickets: 1,
      //   img: "https://static.iplt20.com/players/210/434.png",
      // },
    ],
  },
};

export default SHOP_DATA;
